/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "var(--background)",
        "on-primary-container": "#72869e",
        "surface-variant": "#e4e2e4",
        "on-secondary-container": "#fefcff",
        "surface-container-highest": "#e4e2e4",
        "on-primary-fixed": "#071d31",
        "tertiary-fixed": "#ffdbce",
        "surface-bright": "#fbf9fb",
        "primary-fixed-dim": "#b4c8e3",
        "outline": "#74777d",
        "surface-tint": "#4d6077",
        "secondary-fixed": "#d9e2ff",
        "on-error": "#ffffff",
        "on-background": "#1b1c1d",
        "basari-yesili": "#52C41A",
        "inverse-on-surface": "#f2f0f2",
        "surface-container-high": "var(--surface-container-high)",
        "tertiary-fixed-dim": "#f1baa7",
        "on-tertiary": "#ffffff",
        "surface-container": "var(--surface-container)",
        "inverse-primary": "#b4c8e3",
        "secondary-fixed-dim": "#afc6ff",
        "on-tertiary-container": "#a87967",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "hata-kirmizisi": "#FF4D4F",
        "on-primary-fixed-variant": "#35485e",
        "primary": "#000000",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#301308",
        "surface-container-low": "var(--surface-container-low)",
        "primary-fixed": "#d1e4ff",
        "sidebar-koyu": "var(--sidebar-koyu)",
        "on-surface": "var(--on-surface)",
        "secondary": "var(--secondary)",
        "on-primary": "#ffffff",
        "outline-variant": "var(--outline-variant)",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004398",
        "on-tertiary-fixed-variant": "#633d2f",
        "on-surface-variant": "var(--on-surface-variant)",
        "tertiary-container": "#301308",
        "on-secondary-fixed": "#001a43",
        "primary-container": "#071d31",
        "arka-plan-gri": "var(--arka-plan-gri)",
        "uyari-kehribar": "#FAAD14",
        "on-secondary": "var(--on-secondary)",
        "tertiary": "#000000",
        "surface": "var(--surface)",
        "bilgi-mavisi": "#1677FF",
        "inverse-surface": "#303032",
        "surface-dim": "#dbd9db",
        "secondary-container": "#006ef2"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "grid-olcegi": "4px",
        "standart-padding": "16px",
        "hucre-boslugu": "12px",
        "kenar-payi": "24px",
        "kompakt-padding": "8px"
      },
      fontFamily: {
        "etiket-mono": ["JetBrains Mono"],
        "govde-metin": ["Inter"],
        "ust-baslik-lg": ["Inter"],
        "alt-baslik": ["Inter"],
        "ust-baslik-md": ["Inter"],
        "tablo-verisi": ["Inter"],
        "kucuk-not": ["Inter"]
      },
      fontSize: {
        "etiket-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "govde-metin": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "ust-baslik-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "alt-baslik": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "ust-baslik-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "tablo-verisi": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "kucuk-not": ["12px", { lineHeight: "18px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
